language: objective-c
before_install:

    # install xctool
    - brew update
    - brew remove xctool
    - brew install xctool

    # update cocoapods
    - gem update cocoapods

script: xctool clean build test -arch i386 ONLY_ACTIVE_ARCH=NO
# script: xctool clean build test

notifications:
    email: false
